package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ArticleReply;
import org.linlinjava.litemall.db.domain.ArticleReplyExample;

public interface ArticleReplyMapper {
    long countByExample(ArticleReplyExample example);

    int deleteByExample(ArticleReplyExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(ArticleReply record);

    int insertSelective(ArticleReply record);

    List<ArticleReply> selectByExample(ArticleReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_reply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ArticleReply> selectByExampleSelective(@Param("example") ArticleReplyExample example, @Param("selective") ArticleReply.Column ... selective);

    ArticleReply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_reply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ArticleReply selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ArticleReply.Column ... selective);

    int updateByExampleSelective(@Param("record") ArticleReply record, @Param("example") ArticleReplyExample example);

    int updateByExample(@Param("record") ArticleReply record, @Param("example") ArticleReplyExample example);

    int updateByPrimaryKeySelective(ArticleReply record);

    int updateByPrimaryKey(ArticleReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_reply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ArticleReply selectOneByExample(ArticleReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_reply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ArticleReply selectOneByExampleSelective(@Param("example") ArticleReplyExample example, @Param("selective") ArticleReply.Column ... selective);

    List<ArticleReply> queryByCommentId(ArticleReply reply);
}