package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ArticleCollection;
import org.linlinjava.litemall.db.domain.ArticleCollectionExample;

public interface ArticleCollectionMapper {
    long countByExample(ArticleCollectionExample example);

    int deleteByExample(ArticleCollectionExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(ArticleCollection record);

    int insertSelective(ArticleCollection record);

    List<ArticleCollection> selectByExample(ArticleCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_collection
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ArticleCollection> selectByExampleSelective(@Param("example") ArticleCollectionExample example, @Param("selective") ArticleCollection.Column ... selective);

    ArticleCollection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_collection
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ArticleCollection selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ArticleCollection.Column ... selective);

    int updateByExampleSelective(@Param("record") ArticleCollection record, @Param("example") ArticleCollectionExample example);

    int updateByExample(@Param("record") ArticleCollection record, @Param("example") ArticleCollectionExample example);

    int updateByPrimaryKeySelective(ArticleCollection record);

    int updateByPrimaryKey(ArticleCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_collection
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ArticleCollection selectOneByExample(ArticleCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_collection
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ArticleCollection selectOneByExampleSelective(@Param("example") ArticleCollectionExample example, @Param("selective") ArticleCollection.Column ... selective);
}