package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ArticleNotes;
import org.linlinjava.litemall.db.domain.ArticleNotesExample;

public interface ArticleNotesMapper {
    long countByExample(ArticleNotesExample example);

    int deleteByExample(ArticleNotesExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(ArticleNotes record);

    int insertSelective(ArticleNotes record);

    List<ArticleNotes> selectByExampleWithBLOBs(ArticleNotesExample example);

    List<ArticleNotes> selectByExample(ArticleNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_notes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ArticleNotes> selectByExampleSelective(@Param("example") ArticleNotesExample example, @Param("selective") ArticleNotes.Column ... selective);

    ArticleNotes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_notes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ArticleNotes selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ArticleNotes.Column ... selective);

    int updateByExampleSelective(@Param("record") ArticleNotes record, @Param("example") ArticleNotesExample example);

    int updateByExampleWithBLOBs(@Param("record") ArticleNotes record, @Param("example") ArticleNotesExample example);

    int updateByExample(@Param("record") ArticleNotes record, @Param("example") ArticleNotesExample example);

    int updateByPrimaryKeySelective(ArticleNotes record);

    int updateByPrimaryKeyWithBLOBs(ArticleNotes record);

    int updateByPrimaryKey(ArticleNotes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_notes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ArticleNotes selectOneByExample(ArticleNotesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_notes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ArticleNotes selectOneByExampleSelective(@Param("example") ArticleNotesExample example, @Param("selective") ArticleNotes.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_notes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ArticleNotes selectOneByExampleWithBLOBs(ArticleNotesExample example);
}