package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Checkin;
import org.linlinjava.litemall.db.domain.CheckinExample;

public interface CheckinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    long countByExample(CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int deleteByExample(CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int insert(Checkin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int insertSelective(Checkin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    List<Checkin> selectByExample(CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Checkin> selectByExampleSelective(@Param("example") CheckinExample example, @Param("selective") Checkin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    Checkin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Checkin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Checkin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") Checkin record, @Param("example") CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int updateByExample(@Param("record") Checkin record, @Param("example") CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int updateByPrimaryKeySelective(Checkin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int updateByPrimaryKey(Checkin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Checkin selectOneByExample(CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Checkin selectOneByExampleSelective(@Param("example") CheckinExample example, @Param("selective") Checkin.Column ... selective);
}