package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.CsDetail;
import org.linlinjava.litemall.db.domain.CsDetailExample;

public interface CsDetailMapper {
    long countByExample(CsDetailExample example);

    int deleteByExample(CsDetailExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(CsDetail record);

    int insertSelective(CsDetail record);

    List<CsDetail> selectByExample(CsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<CsDetail> selectByExampleSelective(@Param("example") CsDetailExample example, @Param("selective") CsDetail.Column ... selective);

    CsDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CsDetail selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CsDetail.Column ... selective);

    int updateByExampleSelective(@Param("record") CsDetail record, @Param("example") CsDetailExample example);

    int updateByExample(@Param("record") CsDetail record, @Param("example") CsDetailExample example);

    int updateByPrimaryKeySelective(CsDetail record);

    int updateByPrimaryKey(CsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CsDetail selectOneByExample(CsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CsDetail selectOneByExampleSelective(@Param("example") CsDetailExample example, @Param("selective") CsDetail.Column ... selective);

    Integer sumAccount(@Param("testId") Integer testId,@Param("userId") Integer userId);
}
