package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.CsOption;
import org.linlinjava.litemall.db.domain.CsOptionExample;

public interface CsOptionMapper {
    long countByExample(CsOptionExample example);

    int deleteByExample(CsOptionExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(CsOption record);

    int insertSelective(CsOption record);

    List<CsOption> selectByExample(CsOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_option
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<CsOption> selectByExampleSelective(@Param("example") CsOptionExample example, @Param("selective") CsOption.Column ... selective);

    CsOption selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_option
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CsOption selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CsOption.Column ... selective);

    int updateByExampleSelective(@Param("record") CsOption record, @Param("example") CsOptionExample example);

    int updateByExample(@Param("record") CsOption record, @Param("example") CsOptionExample example);

    int updateByPrimaryKeySelective(CsOption record);

    int updateByPrimaryKey(CsOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_option
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CsOption selectOneByExample(CsOptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_option
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CsOption selectOneByExampleSelective(@Param("example") CsOptionExample example, @Param("selective") CsOption.Column ... selective);
}