package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.CsTitle;
import org.linlinjava.litemall.db.domain.CsTitleExample;

public interface CsTitleMapper {
    long countByExample(CsTitleExample example);

    int deleteByExample(CsTitleExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(CsTitle record);

    int insertSelective(CsTitle record);

    List<CsTitle> selectByExample(CsTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_title
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<CsTitle> selectByExampleSelective(@Param("example") CsTitleExample example, @Param("selective") CsTitle.Column ... selective);

    CsTitle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_title
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CsTitle selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CsTitle.Column ... selective);

    int updateByExampleSelective(@Param("record") CsTitle record, @Param("example") CsTitleExample example);

    int updateByExample(@Param("record") CsTitle record, @Param("example") CsTitleExample example);

    int updateByPrimaryKeySelective(CsTitle record);

    int updateByPrimaryKey(CsTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_title
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CsTitle selectOneByExample(CsTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_title
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CsTitle selectOneByExampleSelective(@Param("example") CsTitleExample example, @Param("selective") CsTitle.Column ... selective);
}