package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.HbPhotoHis;
import org.linlinjava.litemall.db.domain.HbPhotoHisExample;

public interface HbPhotoHisMapper {
    long countByExample(HbPhotoHisExample example);

    int deleteByExample(HbPhotoHisExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(HbPhotoHis record);

    int insertSelective(HbPhotoHis record);

    List<HbPhotoHis> selectByExample(HbPhotoHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_photo_his
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<HbPhotoHis> selectByExampleSelective(@Param("example") HbPhotoHisExample example, @Param("selective") HbPhotoHis.Column ... selective);

    HbPhotoHis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_photo_his
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    HbPhotoHis selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") HbPhotoHis.Column ... selective);

    int updateByExampleSelective(@Param("record") HbPhotoHis record, @Param("example") HbPhotoHisExample example);

    int updateByExample(@Param("record") HbPhotoHis record, @Param("example") HbPhotoHisExample example);

    int updateByPrimaryKeySelective(HbPhotoHis record);

    int updateByPrimaryKey(HbPhotoHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_photo_his
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    HbPhotoHis selectOneByExample(HbPhotoHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hb_photo_his
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    HbPhotoHis selectOneByExampleSelective(@Param("example") HbPhotoHisExample example, @Param("selective") HbPhotoHis.Column ... selective);
}