package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Integretion;
import org.linlinjava.litemall.db.domain.IntegretionExample;

public interface IntegretionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    long countByExample(IntegretionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int deleteByExample(IntegretionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int deleteByPrimaryKey(Integer integretionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int insert(Integretion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int insertSelective(Integretion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    List<Integretion> selectByExample(IntegretionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Integretion> selectByExampleSelective(@Param("example") IntegretionExample example, @Param("selective") Integretion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    Integretion selectByPrimaryKey(Integer integretionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Integretion selectByPrimaryKeySelective(@Param("integretionId") Integer integretionId, @Param("selective") Integretion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") Integretion record, @Param("example") IntegretionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int updateByExample(@Param("record") Integretion record, @Param("example") IntegretionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int updateByPrimaryKeySelective(Integretion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int updateByPrimaryKey(Integretion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Integretion selectOneByExample(IntegretionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Integretion selectOneByExampleSelective(@Param("example") IntegretionExample example, @Param("selective") Integretion.Column ... selective);
}