package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.IntegretionDetail;
import org.linlinjava.litemall.db.domain.IntegretionDetailExample;

public interface IntegretionDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion_detail
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    long countByExample(IntegretionDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion_detail
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int deleteByExample(IntegretionDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion_detail
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion_detail
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int insert(IntegretionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion_detail
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int insertSelective(IntegretionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion_detail
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    List<IntegretionDetail> selectByExample(IntegretionDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<IntegretionDetail> selectByExampleSelective(@Param("example") IntegretionDetailExample example, @Param("selective") IntegretionDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion_detail
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    IntegretionDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    IntegretionDetail selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IntegretionDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion_detail
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") IntegretionDetail record, @Param("example") IntegretionDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion_detail
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int updateByExample(@Param("record") IntegretionDetail record, @Param("example") IntegretionDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion_detail
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int updateByPrimaryKeySelective(IntegretionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion_detail
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int updateByPrimaryKey(IntegretionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    IntegretionDetail selectOneByExample(IntegretionDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    IntegretionDetail selectOneByExampleSelective(@Param("example") IntegretionDetailExample example, @Param("selective") IntegretionDetail.Column ... selective);
}