package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LetterReply;
import org.linlinjava.litemall.db.domain.LetterReplyExample;

public interface LetterReplyMapper {
    long countByExample(LetterReplyExample example);

    int deleteByExample(LetterReplyExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(LetterReply record);

    int insertSelective(LetterReply record);

    List<LetterReply> selectByExample(LetterReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table letter_reply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LetterReply> selectByExampleSelective(@Param("example") LetterReplyExample example, @Param("selective") LetterReply.Column ... selective);

    LetterReply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table letter_reply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LetterReply selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LetterReply.Column ... selective);

    int updateByExampleSelective(@Param("record") LetterReply record, @Param("example") LetterReplyExample example);

    int updateByExample(@Param("record") LetterReply record, @Param("example") LetterReplyExample example);

    int updateByPrimaryKeySelective(LetterReply record);

    int updateByPrimaryKey(LetterReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table letter_reply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LetterReply selectOneByExample(LetterReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table letter_reply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LetterReply selectOneByExampleSelective(@Param("example") LetterReplyExample example, @Param("selective") LetterReply.Column ... selective);
}