package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Medal;
import org.linlinjava.litemall.db.domain.MedalExample;

public interface MedalMapper {
    long countByExample(MedalExample example);

    int deleteByExample(MedalExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(Medal record);

    int insertSelective(Medal record);

    List<Medal> selectByExample(MedalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medal
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Medal> selectByExampleSelective(@Param("example") MedalExample example, @Param("selective") Medal.Column ... selective);

    Medal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medal
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Medal selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Medal.Column ... selective);

    int updateByExampleSelective(@Param("record") Medal record, @Param("example") MedalExample example);

    int updateByExample(@Param("record") Medal record, @Param("example") MedalExample example);

    int updateByPrimaryKeySelective(Medal record);

    int updateByPrimaryKey(Medal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medal
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Medal selectOneByExample(MedalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medal
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Medal selectOneByExampleSelective(@Param("example") MedalExample example, @Param("selective") Medal.Column ... selective);
}