package org.linlinjava.litemall.db.dao;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.NotesTemp;
import org.linlinjava.litemall.db.domain.NotesTempExample;

import java.util.List;

public interface NotesTempMapper {
    long countByExample(NotesTempExample example);

    int deleteByExample(NotesTempExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(NotesTemp record);

    int insertSelective(NotesTemp record);

    List<NotesTemp> selectByExample(NotesTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes_temp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<NotesTemp> selectByExampleSelective(@Param("example") NotesTempExample example, @Param("selective") NotesTemp.Column ... selective);

    NotesTemp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes_temp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    NotesTemp selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") NotesTemp.Column ... selective);

    int updateByExampleSelective(@Param("record") NotesTemp record, @Param("example") NotesTempExample example);

    int updateByExample(@Param("record") NotesTemp record, @Param("example") NotesTempExample example);

    int updateByPrimaryKeySelective(NotesTemp record);

    int updateByPrimaryKey(NotesTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes_temp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    NotesTemp selectOneByExample(NotesTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notes_temp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    NotesTemp selectOneByExampleSelective(@Param("example") NotesTempExample example, @Param("selective") NotesTemp.Column ... selective);
}