package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Praise;
import org.linlinjava.litemall.db.domain.PraiseExample;

public interface PraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    long countByExample(PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int deleteByExample(PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int insert(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int insertSelective(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    List<Praise> selectByExample(PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Praise> selectByExampleSelective(@Param("example") PraiseExample example, @Param("selective") Praise.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    Praise selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Praise selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Praise.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") Praise record, @Param("example") PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int updateByExample(@Param("record") Praise record, @Param("example") PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int updateByPrimaryKeySelective(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    int updateByPrimaryKey(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Praise selectOneByExample(PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Praise selectOneByExampleSelective(@Param("example") PraiseExample example, @Param("selective") Praise.Column ... selective);
}