package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.PraiseComment;
import org.linlinjava.litemall.db.domain.PraiseCommentExample;

public interface PraiseCommentMapper {
    long countByExample(PraiseCommentExample example);

    int deleteByExample(PraiseCommentExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(PraiseComment record);

    int insertSelective(PraiseComment record);

    List<PraiseComment> selectByExample(PraiseCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<PraiseComment> selectByExampleSelective(@Param("example") PraiseCommentExample example, @Param("selective") PraiseComment.Column ... selective);

    PraiseComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PraiseComment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") PraiseComment.Column ... selective);

    int updateByExampleSelective(@Param("record") PraiseComment record, @Param("example") PraiseCommentExample example);

    int updateByExample(@Param("record") PraiseComment record, @Param("example") PraiseCommentExample example);

    int updateByPrimaryKeySelective(PraiseComment record);

    int updateByPrimaryKey(PraiseComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PraiseComment selectOneByExample(PraiseCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise_comment
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    PraiseComment selectOneByExampleSelective(@Param("example") PraiseCommentExample example, @Param("selective") PraiseComment.Column ... selective);
}