package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.SysCorps;
import org.linlinjava.litemall.db.domain.SysCorpsExample;

public interface SysCorpsMapper {
    long countByExample(SysCorpsExample example);

    int deleteByExample(SysCorpsExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(SysCorps record);

    int insertSelective(SysCorps record);

    List<SysCorps> selectByExample(SysCorpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_corps
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SysCorps> selectByExampleSelective(@Param("example") SysCorpsExample example, @Param("selective") SysCorps.Column ... selective);

    SysCorps selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_corps
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysCorps selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SysCorps.Column ... selective);

    int updateByExampleSelective(@Param("record") SysCorps record, @Param("example") SysCorpsExample example);

    int updateByExample(@Param("record") SysCorps record, @Param("example") SysCorpsExample example);

    int updateByPrimaryKeySelective(SysCorps record);

    int updateByPrimaryKey(SysCorps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_corps
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysCorps selectOneByExample(SysCorpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_corps
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysCorps selectOneByExampleSelective(@Param("example") SysCorpsExample example, @Param("selective") SysCorps.Column ... selective);
}