package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.SysTransition;
import org.linlinjava.litemall.db.domain.SysTransitionExample;

public interface SysTransitionMapper {
    long countByExample(SysTransitionExample example);

    int deleteByExample(SysTransitionExample example);

    int insert(SysTransition record);

    int insertSelective(SysTransition record);

    List<SysTransition> selectByExample(SysTransitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_transition
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SysTransition> selectByExampleSelective(@Param("example") SysTransitionExample example, @Param("selective") SysTransition.Column ... selective);

    int updateByExampleSelective(@Param("record") SysTransition record, @Param("example") SysTransitionExample example);

    int updateByExample(@Param("record") SysTransition record, @Param("example") SysTransitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_transition
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysTransition selectOneByExample(SysTransitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_transition
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysTransition selectOneByExampleSelective(@Param("example") SysTransitionExample example, @Param("selective") SysTransition.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_transition
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysTransition selectByPrimaryKeySelective(@Param("selective") SysTransition.Column ... selective);
}