package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.WxConfig;
import org.linlinjava.litemall.db.domain.WxConfigExample;

public interface WxConfigMapper {
    long countByExample(WxConfigExample example);

    int deleteByExample(WxConfigExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(WxConfig record);

    int insertSelective(WxConfig record);

    List<WxConfig> selectByExample(WxConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<WxConfig> selectByExampleSelective(@Param("example") WxConfigExample example, @Param("selective") WxConfig.Column ... selective);

    WxConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxConfig selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WxConfig.Column ... selective);

    int updateByExampleSelective(@Param("record") WxConfig record, @Param("example") WxConfigExample example);

    int updateByExample(@Param("record") WxConfig record, @Param("example") WxConfigExample example);

    int updateByPrimaryKeySelective(WxConfig record);

    int updateByPrimaryKey(WxConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxConfig selectOneByExample(WxConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxConfig selectOneByExampleSelective(@Param("example") WxConfigExample example, @Param("selective") WxConfig.Column ... selective);
}