package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.WxFormid;
import org.linlinjava.litemall.db.domain.WxFormidExample;

public interface WxFormidMapper {
    long countByExample(WxFormidExample example);

    int deleteByExample(WxFormidExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(WxFormid record);

    int insertSelective(WxFormid record);

    List<WxFormid> selectByExample(WxFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<WxFormid> selectByExampleSelective(@Param("example") WxFormidExample example, @Param("selective") WxFormid.Column ... selective);

    WxFormid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxFormid selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WxFormid.Column ... selective);

    int updateByExampleSelective(@Param("record") WxFormid record, @Param("example") WxFormidExample example);

    int updateByExample(@Param("record") WxFormid record, @Param("example") WxFormidExample example);

    int updateByPrimaryKeySelective(WxFormid record);

    int updateByPrimaryKey(WxFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxFormid selectOneByExample(WxFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxFormid selectOneByExampleSelective(@Param("example") WxFormidExample example, @Param("selective") WxFormid.Column ... selective);
}