package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.WxGzhUser;
import org.linlinjava.litemall.db.domain.WxGzhUserExample;

public interface WxGzhUserMapper {
    long countByExample(WxGzhUserExample example);

    int deleteByExample(WxGzhUserExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(WxGzhUser record);

    int insertSelective(WxGzhUser record);

    List<WxGzhUser> selectByExample(WxGzhUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_gzh_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<WxGzhUser> selectByExampleSelective(@Param("example") WxGzhUserExample example, @Param("selective") WxGzhUser.Column ... selective);

    WxGzhUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_gzh_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxGzhUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WxGzhUser.Column ... selective);

    int updateByExampleSelective(@Param("record") WxGzhUser record, @Param("example") WxGzhUserExample example);

    int updateByExample(@Param("record") WxGzhUser record, @Param("example") WxGzhUserExample example);

    int updateByPrimaryKeySelective(WxGzhUser record);

    int updateByPrimaryKey(WxGzhUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_gzh_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxGzhUser selectOneByExample(WxGzhUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_gzh_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxGzhUser selectOneByExampleSelective(@Param("example") WxGzhUserExample example, @Param("selective") WxGzhUser.Column ... selective);
}