package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.WxMenu;
import org.linlinjava.litemall.db.domain.WxMenuExample;

public interface WxMenuMapper {
    long countByExample(WxMenuExample example);

    int deleteByExample(WxMenuExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(WxMenu record);

    int insertSelective(WxMenu record);

    List<WxMenu> selectByExample(WxMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<WxMenu> selectByExampleSelective(@Param("example") WxMenuExample example, @Param("selective") WxMenu.Column ... selective);

    WxMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxMenu selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WxMenu.Column ... selective);

    int updateByExampleSelective(@Param("record") WxMenu record, @Param("example") WxMenuExample example);

    int updateByExample(@Param("record") WxMenu record, @Param("example") WxMenuExample example);

    int updateByPrimaryKeySelective(WxMenu record);

    int updateByPrimaryKey(WxMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxMenu selectOneByExample(WxMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxMenu selectOneByExampleSelective(@Param("example") WxMenuExample example, @Param("selective") WxMenu.Column ... selective);
}