package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.WxMess;
import org.linlinjava.litemall.db.domain.WxMessExample;

public interface WxMessMapper {
    long countByExample(WxMessExample example);

    int deleteByExample(WxMessExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(WxMess record);

    int insertSelective(WxMess record);

    List<WxMess> selectByExample(WxMessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mess
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<WxMess> selectByExampleSelective(@Param("example") WxMessExample example, @Param("selective") WxMess.Column ... selective);

    WxMess selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mess
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxMess selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WxMess.Column ... selective);

    int updateByExampleSelective(@Param("record") WxMess record, @Param("example") WxMessExample example);

    int updateByExample(@Param("record") WxMess record, @Param("example") WxMessExample example);

    int updateByPrimaryKeySelective(WxMess record);

    int updateByPrimaryKey(WxMess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mess
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxMess selectOneByExample(WxMessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_mess
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxMess selectOneByExampleSelective(@Param("example") WxMessExample example, @Param("selective") WxMess.Column ... selective);
}