package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.WxTempleteSendStatus;
import org.linlinjava.litemall.db.domain.WxTempleteSendStatusExample;

public interface WxTempleteSendStatusMapper {
    long countByExample(WxTempleteSendStatusExample example);

    int deleteByExample(WxTempleteSendStatusExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(WxTempleteSendStatus record);

    int insertSelective(WxTempleteSendStatus record);

    List<WxTempleteSendStatus> selectByExample(WxTempleteSendStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_templete_send_status
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<WxTempleteSendStatus> selectByExampleSelective(@Param("example") WxTempleteSendStatusExample example, @Param("selective") WxTempleteSendStatus.Column ... selective);

    WxTempleteSendStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_templete_send_status
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxTempleteSendStatus selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WxTempleteSendStatus.Column ... selective);

    int updateByExampleSelective(@Param("record") WxTempleteSendStatus record, @Param("example") WxTempleteSendStatusExample example);

    int updateByExample(@Param("record") WxTempleteSendStatus record, @Param("example") WxTempleteSendStatusExample example);

    int updateByPrimaryKeySelective(WxTempleteSendStatus record);

    int updateByPrimaryKey(WxTempleteSendStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_templete_send_status
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxTempleteSendStatus selectOneByExample(WxTempleteSendStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_templete_send_status
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxTempleteSendStatus selectOneByExampleSelective(@Param("example") WxTempleteSendStatusExample example, @Param("selective") WxTempleteSendStatus.Column ... selective);

    List<WxTempleteSendStatus> queryByList(WxTempleteSendStatusExample example);
}