package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.WxTempleteSend;
import org.linlinjava.litemall.db.domain.WxTempleteSendExample;

public interface WxTempleteSendMapper {
    long countByExample(WxTempleteSendExample example);

    int deleteByExample(WxTempleteSendExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(WxTempleteSend record);

    int insertSelective(WxTempleteSend record);

    List<WxTempleteSend> selectByExample(WxTempleteSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_templete_send
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<WxTempleteSend> selectByExampleSelective(@Param("example") WxTempleteSendExample example, @Param("selective") WxTempleteSend.Column ... selective);

    WxTempleteSend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_templete_send
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxTempleteSend selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") WxTempleteSend.Column ... selective);

    int updateByExampleSelective(@Param("record") WxTempleteSend record, @Param("example") WxTempleteSendExample example);

    int updateByExample(@Param("record") WxTempleteSend record, @Param("example") WxTempleteSendExample example);

    int updateByPrimaryKeySelective(WxTempleteSend record);

    int updateByPrimaryKey(WxTempleteSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_templete_send
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxTempleteSend selectOneByExample(WxTempleteSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_templete_send
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    WxTempleteSend selectOneByExampleSelective(@Param("example") WxTempleteSendExample example, @Param("selective") WxTempleteSend.Column ... selective);
}