package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ZkArea;
import org.linlinjava.litemall.db.domain.ZkAreaExample;

public interface ZkAreaMapper {
    long countByExample(ZkAreaExample example);

    int deleteByExample(ZkAreaExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(ZkArea record);

    int insertSelective(ZkArea record);

    List<ZkArea> selectByExample(ZkAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_area
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ZkArea> selectByExampleSelective(@Param("example") ZkAreaExample example, @Param("selective") ZkArea.Column ... selective);

    ZkArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_area
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZkArea selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ZkArea.Column ... selective);

    int updateByExampleSelective(@Param("record") ZkArea record, @Param("example") ZkAreaExample example);

    int updateByExample(@Param("record") ZkArea record, @Param("example") ZkAreaExample example);

    int updateByPrimaryKeySelective(ZkArea record);

    int updateByPrimaryKey(ZkArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_area
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZkArea selectOneByExample(ZkAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_area
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZkArea selectOneByExampleSelective(@Param("example") ZkAreaExample example, @Param("selective") ZkArea.Column ... selective);
}