package org.linlinjava.litemall.db.dao;

import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ZkTiku;
import org.linlinjava.litemall.db.domain.ZkTikuExample;

import java.util.List;

public interface ZkTikuMapper {
    long countByExample(ZkTikuExample example);

    int deleteByExample(ZkTikuExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(ZkTiku record);

    int insertSelective(ZkTiku record);

    List<ZkTiku> selectByExample(ZkTikuExample example);

    List<ZkTiku> selectByExample2(ZkTikuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_tiku
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ZkTiku> selectByExampleSelective(@Param("example") ZkTikuExample example, @Param("selective") ZkTiku.Column ... selective);

    ZkTiku selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_tiku
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZkTiku selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ZkTiku.Column ... selective);

    int updateByExampleSelective(@Param("record") ZkTiku record, @Param("example") ZkTikuExample example);

    int updateByExample(@Param("record") ZkTiku record, @Param("example") ZkTikuExample example);

    int updateByPrimaryKeySelective(ZkTiku record);

    int updateByPrimaryKey(ZkTiku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_tiku
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZkTiku selectOneByExample(ZkTikuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_tiku
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZkTiku selectOneByExampleSelective(@Param("example") ZkTikuExample example, @Param("selective") ZkTiku.Column ... selective);
}