package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ZkTikuDetail;
import org.linlinjava.litemall.db.domain.ZkTikuDetailExample;

public interface ZkTikuDetailMapper {
    long countByExample(ZkTikuDetailExample example);

    int deleteByExample(ZkTikuDetailExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(ZkTikuDetail record);

    int insertSelective(ZkTikuDetail record);

    List<ZkTikuDetail> selectByExample(ZkTikuDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_tiku_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ZkTikuDetail> selectByExampleSelective(@Param("example") ZkTikuDetailExample example, @Param("selective") ZkTikuDetail.Column ... selective);

    ZkTikuDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_tiku_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZkTikuDetail selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ZkTikuDetail.Column ... selective);

    int updateByExampleSelective(@Param("record") ZkTikuDetail record, @Param("example") ZkTikuDetailExample example);

    int updateByExample(@Param("record") ZkTikuDetail record, @Param("example") ZkTikuDetailExample example);

    int updateByPrimaryKeySelective(ZkTikuDetail record);

    int updateByPrimaryKey(ZkTikuDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_tiku_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZkTikuDetail selectOneByExample(ZkTikuDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_tiku_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZkTikuDetail selectOneByExampleSelective(@Param("example") ZkTikuDetailExample example, @Param("selective") ZkTikuDetail.Column ... selective);
}