package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ZkZhuanye;
import org.linlinjava.litemall.db.domain.ZkZhuanyeExample;

public interface ZkZhuanyeMapper {
    long countByExample(ZkZhuanyeExample example);

    int deleteByExample(ZkZhuanyeExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(ZkZhuanye record);

    int insertSelective(ZkZhuanye record);

    List<ZkZhuanye> selectByExample(ZkZhuanyeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_zhuanye
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ZkZhuanye> selectByExampleSelective(@Param("example") ZkZhuanyeExample example, @Param("selective") ZkZhuanye.Column ... selective);

    ZkZhuanye selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_zhuanye
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZkZhuanye selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ZkZhuanye.Column ... selective);

    int updateByExampleSelective(@Param("record") ZkZhuanye record, @Param("example") ZkZhuanyeExample example);

    int updateByExample(@Param("record") ZkZhuanye record, @Param("example") ZkZhuanyeExample example);

    int updateByPrimaryKeySelective(ZkZhuanye record);

    int updateByPrimaryKey(ZkZhuanye record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_zhuanye
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZkZhuanye selectOneByExample(ZkZhuanyeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_zhuanye
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ZkZhuanye selectOneByExampleSelective(@Param("example") ZkZhuanyeExample example, @Param("selective") ZkZhuanye.Column ... selective);
}