package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;

public class ArticleNotes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_notes.id
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_notes.artile_id
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    private Integer artileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_notes.name
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_notes.no
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_notes.create_date
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_notes.sort_no
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    private Integer sortNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_notes.status
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_notes.content
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_notes.id
     *
     * @return the value of article_notes.id
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_notes.id
     *
     * @param id the value for article_notes.id
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_notes.artile_id
     *
     * @return the value of article_notes.artile_id
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public Integer getArtileId() {
        return artileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_notes.artile_id
     *
     * @param artileId the value for article_notes.artile_id
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public void setArtileId(Integer artileId) {
        this.artileId = artileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_notes.name
     *
     * @return the value of article_notes.name
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_notes.name
     *
     * @param name the value for article_notes.name
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_notes.no
     *
     * @return the value of article_notes.no
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_notes.no
     *
     * @param no the value for article_notes.no
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_notes.create_date
     *
     * @return the value of article_notes.create_date
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_notes.create_date
     *
     * @param createDate the value for article_notes.create_date
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_notes.sort_no
     *
     * @return the value of article_notes.sort_no
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_notes.sort_no
     *
     * @param sortNo the value for article_notes.sort_no
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_notes.status
     *
     * @return the value of article_notes.status
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_notes.status
     *
     * @param status the value for article_notes.status
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_notes.content
     *
     * @return the value of article_notes.content
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_notes.content
     *
     * @param content the value for article_notes.content
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_notes
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", artileId=").append(artileId);
        sb.append(", name=").append(name);
        sb.append(", no=").append(no);
        sb.append(", createDate=").append(createDate);
        sb.append(", sortNo=").append(sortNo);
        sb.append(", status=").append(status);
        sb.append(", content=").append(content);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_notes
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ArticleNotes other = (ArticleNotes) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getArtileId() == null ? other.getArtileId() == null : this.getArtileId().equals(other.getArtileId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getNo() == null ? other.getNo() == null : this.getNo().equals(other.getNo()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getSortNo() == null ? other.getSortNo() == null : this.getSortNo().equals(other.getSortNo()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_notes
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getArtileId() == null) ? 0 : getArtileId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getNo() == null) ? 0 : getNo().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getSortNo() == null) ? 0 : getSortNo().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table article_notes
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        artileId("artile_id"),
        name("name"),
        no("no"),
        createDate("create_date"),
        sortNo("sort_no"),
        status("status"),
        content("content");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table article_notes
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table article_notes
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table article_notes
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table article_notes
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table article_notes
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table article_notes
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}