package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;

public class Integretion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integretion.integretion_id
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    private Integer integretionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integretion.user_id
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integretion.amount
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integretion.status
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integretion.create_date
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    private LocalDateTime createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integretion.integretion_id
     *
     * @return the value of integretion.integretion_id
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public Integer getIntegretionId() {
        return integretionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integretion.integretion_id
     *
     * @param integretionId the value for integretion.integretion_id
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public void setIntegretionId(Integer integretionId) {
        this.integretionId = integretionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integretion.user_id
     *
     * @return the value of integretion.user_id
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integretion.user_id
     *
     * @param userId the value for integretion.user_id
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integretion.amount
     *
     * @return the value of integretion.amount
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integretion.amount
     *
     * @param amount the value for integretion.amount
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integretion.status
     *
     * @return the value of integretion.status
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integretion.status
     *
     * @param status the value for integretion.status
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integretion.create_date
     *
     * @return the value of integretion.create_date
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integretion.create_date
     *
     * @param createDate the value for integretion.create_date
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", integretionId=").append(integretionId);
        sb.append(", userId=").append(userId);
        sb.append(", amount=").append(amount);
        sb.append(", status=").append(status);
        sb.append(", createDate=").append(createDate);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Integretion other = (Integretion) that;
        return (this.getIntegretionId() == null ? other.getIntegretionId() == null : this.getIntegretionId().equals(other.getIntegretionId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table integretion
     *
     * @mbg.generated Sat Apr 28 16:57:49 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIntegretionId() == null) ? 0 : getIntegretionId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table integretion
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        integretionId("integretion_id"),
        userId("user_id"),
        amount("amount"),
        status("status"),
        createDate("create_date");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table integretion
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table integretion
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table integretion
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table integretion
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table integretion
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table integretion
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}